// Generated by gencpp from file turtlesim_game/GetGameStats.msg
// DO NOT EDIT!


#ifndef TURTLESIM_GAME_MESSAGE_GETGAMESTATS_H
#define TURTLESIM_GAME_MESSAGE_GETGAMESTATS_H

#include <ros/service_traits.h>


#include <turtlesim_game/GetGameStatsRequest.h>
#include <turtlesim_game/GetGameStatsResponse.h>


namespace turtlesim_game
{

struct GetGameStats
{

typedef GetGameStatsRequest Request;
typedef GetGameStatsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGameStats
} // namespace turtlesim_game


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim_game::GetGameStats > {
  static const char* value()
  {
    return "7c5d5a8df822594016cbcf60c0ddc011";
  }

  static const char* value(const ::turtlesim_game::GetGameStats&) { return value(); }
};

template<>
struct DataType< ::turtlesim_game::GetGameStats > {
  static const char* value()
  {
    return "turtlesim_game/GetGameStats";
  }

  static const char* value(const ::turtlesim_game::GetGameStats&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim_game::GetGameStatsRequest> should match
// service_traits::MD5Sum< ::turtlesim_game::GetGameStats >
template<>
struct MD5Sum< ::turtlesim_game::GetGameStatsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_game::GetGameStats >::value();
  }
  static const char* value(const ::turtlesim_game::GetGameStatsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_game::GetGameStatsRequest> should match
// service_traits::DataType< ::turtlesim_game::GetGameStats >
template<>
struct DataType< ::turtlesim_game::GetGameStatsRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim_game::GetGameStats >::value();
  }
  static const char* value(const ::turtlesim_game::GetGameStatsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim_game::GetGameStatsResponse> should match
// service_traits::MD5Sum< ::turtlesim_game::GetGameStats >
template<>
struct MD5Sum< ::turtlesim_game::GetGameStatsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_game::GetGameStats >::value();
  }
  static const char* value(const ::turtlesim_game::GetGameStatsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_game::GetGameStatsResponse> should match
// service_traits::DataType< ::turtlesim_game::GetGameStats >
template<>
struct DataType< ::turtlesim_game::GetGameStatsResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim_game::GetGameStats >::value();
  }
  static const char* value(const ::turtlesim_game::GetGameStatsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_GAME_MESSAGE_GETGAMESTATS_H
